import type { WeeklySession, Camp, PrivateSlot } from "./sheets";

export const demoWeeklySchedule: WeeklySession[] = [
  { group: "Junior Boys & Girls — Grade 5 & Below", date: "March 24, 2026", startTime: "5:00 PM", endTime: "6:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Junior Boys & Girls — Grade 5 & Below", date: "March 26, 2026", startTime: "5:00 PM", endTime: "6:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Junior Boys & Girls — Grade 5 & Below", date: "March 28, 2026", startTime: "9:00 AM", endTime: "10:00 AM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Junior Boys & Girls — Grade 5 & Below", date: "March 31, 2026", startTime: "5:00 PM", endTime: "6:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Junior Boys & Girls — Grade 5 & Below", date: "April 2, 2026", startTime: "5:00 PM", endTime: "6:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Junior Boys & Girls — Grade 5 & Below", date: "April 4, 2026", startTime: "9:00 AM", endTime: "10:00 AM", location: "St. Pauls", maxSpots: 6, price: 50 },

  { group: "Middle School Boys — Grades 5-8", date: "March 24, 2026", startTime: "6:00 PM", endTime: "7:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Middle School Boys — Grades 5-8", date: "March 26, 2026", startTime: "6:00 PM", endTime: "7:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Middle School Boys — Grades 5-8", date: "March 28, 2026", startTime: "10:00 AM", endTime: "11:00 AM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Middle School Boys — Grades 5-8", date: "March 31, 2026", startTime: "6:00 PM", endTime: "7:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Middle School Boys — Grades 5-8", date: "April 2, 2026", startTime: "6:00 PM", endTime: "7:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Middle School Boys — Grades 5-8", date: "April 4, 2026", startTime: "10:00 AM", endTime: "11:00 AM", location: "St. Pauls", maxSpots: 6, price: 50 },

  { group: "Middle School Girls — Grades 5-8", date: "March 24, 2026", startTime: "7:00 PM", endTime: "8:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Middle School Girls — Grades 5-8", date: "March 26, 2026", startTime: "7:00 PM", endTime: "8:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Middle School Girls — Grades 5-8", date: "March 28, 2026", startTime: "11:00 AM", endTime: "12:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Middle School Girls — Grades 5-8", date: "March 31, 2026", startTime: "7:00 PM", endTime: "8:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "Middle School Girls — Grades 5-8", date: "April 2, 2026", startTime: "7:00 PM", endTime: "8:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },

  { group: "High School Girls — Grades 9-12", date: "March 24, 2026", startTime: "5:00 PM", endTime: "6:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "High School Girls — Grades 9-12", date: "March 27, 2026", startTime: "5:00 PM", endTime: "6:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "High School Girls — Grades 9-12", date: "March 29, 2026", startTime: "2:30 PM", endTime: "3:30 PM", location: "Cherry Valley", maxSpots: 6, price: 50 },
  { group: "High School Girls — Grades 9-12", date: "March 31, 2026", startTime: "5:00 PM", endTime: "6:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "High School Girls — Grades 9-12", date: "April 3, 2026", startTime: "5:00 PM", endTime: "6:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },

  { group: "High School Boys — Grades 9-12", date: "March 24, 2026", startTime: "6:00 PM", endTime: "7:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "High School Boys — Grades 9-12", date: "March 27, 2026", startTime: "6:00 PM", endTime: "7:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "High School Boys — Grades 9-12", date: "March 29, 2026", startTime: "3:30 PM", endTime: "4:30 PM", location: "Cherry Valley", maxSpots: 6, price: 50 },
  { group: "High School Boys — Grades 9-12", date: "March 31, 2026", startTime: "6:00 PM", endTime: "7:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
  { group: "High School Boys — Grades 9-12", date: "April 3, 2026", startTime: "6:00 PM", endTime: "7:00 PM", location: "St. Pauls", maxSpots: 6, price: 50 },
];

export const demoCamps: Camp[] = [
  {
    id: "camp-0",
    name: "April Break Skills Camp",
    startDate: "April 2-3 & 6-7, 2026",
    endDate: "",
    time: "8:00-10:00 AM",
    location: "St. Paul's Cathedral",
    maxSpots: 8,
    currentEnrolled: 0,
    price: "$375",
    description: "SMALL GROUPS | HIGH INTENSITY | REAL IMPROVEMENT",
    notify: false,
    gradeGroup: "Grades 3-5",
    earlyBirdPrice: "$290",
    dropInPrice: "$100",
    campDays: ["April 2", "April 3", "April 6", "April 7"],
  },
  {
    id: "camp-1",
    name: "April Break Skills Camp",
    startDate: "April 2-3 & 6-7, 2026",
    endDate: "",
    time: "10:00 AM-12:00 PM",
    location: "St. Paul's Cathedral",
    maxSpots: 8,
    currentEnrolled: 0,
    price: "$375",
    description: "SMALL GROUPS | HIGH INTENSITY | REAL IMPROVEMENT",
    notify: false,
    gradeGroup: "Grades 6-8",
    earlyBirdPrice: "$290",
    dropInPrice: "$100",
    campDays: ["April 2", "April 3", "April 6", "April 7"],
  },
  {
    id: "camp-2",
    name: "April Break Skills Camp",
    startDate: "April 2-3 & 6-7, 2026",
    endDate: "",
    time: "12:00-2:00 PM",
    location: "St. Paul's Cathedral",
    maxSpots: 8,
    currentEnrolled: 0,
    price: "$375",
    description: "SMALL GROUPS | HIGH INTENSITY | REAL IMPROVEMENT",
    notify: false,
    gradeGroup: "Grades 9-12",
    earlyBirdPrice: "$290",
    dropInPrice: "$100",
    campDays: ["April 2", "April 3", "April 6", "April 7"],
  },
];

export const demoPrivateSlots: PrivateSlot[] = [
  { id: "slot-0", date: "March 22, 2026", startTime: "4:00 PM", endTime: "5:00 PM", location: "St. Pauls", available: true },
  { id: "slot-1", date: "March 23, 2026", startTime: "3:00 PM", endTime: "4:00 PM", location: "St. Pauls", available: true },
  { id: "slot-2", date: "March 25, 2026", startTime: "4:00 PM", endTime: "5:00 PM", location: "Cherry Valley", available: true },
  { id: "slot-3", date: "March 29, 2026", startTime: "10:00 AM", endTime: "11:00 AM", location: "St. Pauls", available: true },
  { id: "slot-4", date: "March 29, 2026", startTime: "3:00 PM", endTime: "3:45 PM", location: "St. Pauls", available: true },
  { id: "slot-5", date: "March 30, 2026", startTime: "2:00 PM", endTime: "3:00 PM", location: "St. Pauls", available: true },
];
